### PR TITLE
Adds dw lib

### PR DESCRIPTION
**Pull request by jam01**
Hey guys, here we're adding a new library. It's not 100%, but we felt it's at a decent enough for you guys to consider and provide feedback if there's something you guys would like to change. Also if merged it should help us start providing smaller changes as they come and prevent us from falling out of sync too long.

cc: @JakeMHughes @k2merlinsix

### CODE REVIEW

**Comment by fugu13** [comment]
@jam01 Heya! Just wanted to let you know I'm very excited to look over this and just haven't had a chance yet (the camel contribution too), this week has just been packed with stuff so I haven't had a chance yet

**Comment by javaduke** [comment]
Would it be possible for you to provide a documentation on this library, if possible, following the same format as our DataSonnet library documentation?

**Comment by JakeMHughes** [comment]
I did build out a large documentation file for DS-Playground you can view here : https://github.com/JakeMHughes/DS-Playground/blob/master/docs/documentation.md (DW functions are below std and DS)
But a good majority of the descriptions are copied and pasted from DataWeave's documentation with just minor changes. Would that be a problem or would you rather have it recreated?

**Comment by fugu13** [comment]
Hmm, we definitely can't copy their descriptions (copyright and all that), most likely we'll just compromise on signatures + explanation of differences + links, what do you think about that as an approach?

**Comment by fugu13** [comment]
Oh, and where there's overlap with the primary datasonnet libraries we should link those and recommend people migrate to them over time

**Comment by JakeMHughes** [comment]
So just to make sure I understand, something like this?

### sum(array arr)
[DataWeave Documentation](https://docs.mulesoft.com/mule-runtime/4.3/dw-core-functions-sum#sum1)
Differences: This is an example difference. ( dont include if no differences)

[DataSonnet Version](#) (Dont include if no option)

Example
```
DW.Core.sum([10, 20, 30])
```
Result
```
60
```

**Comment by fugu13** [comment]
Yeah, I think that looks excellent. Let's make the "DataSonnet Version" link a short sentence. Maybe "This function has a native DataSonnet Version" (with last words linkified)? And then we're off to the races!

**Comment by JakeMHughes** [comment]
I added the file : `docs/modules/ROOT/pages/dw-libraries.adoc` I think it follows the libraries.adoc file pretty closely so hopefully the formatting is correct and i used the xref key properly (I'm not too familiar with asciidocs).

Otherwise I generally followed the example above and I also did the same if sjsonnet had a native function.

**Comment by javaduke** [comment]
@jam01 Any reason why you closed this?

**Comment by k2merlinsix** [comment]
In the past few weeks since we made the PR we have re-evaluated what we have created and feel that there is a better way to do this.  We will modify the code and submit a new PR when its ready

**Comment by fugu13** [comment]
@k2merlinsix makes sense, and we're good with proceeding with either direction. We're hoping to expand the current libraries some too, we've got a bunch of potential ideas... just very little execution time

**Pull request closed without merging**
